# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    body_converter:
        enabled: true
    view:
        formats: { json: true, xml: false, rss: false }
    serializer:
        serialize_null: true
    service:
        serializer: "fos_rest.serializer.jms"
    format_listener:
        rules:
            - { path: '^/', priorities: [ 'json' ], fallback_format: 'json' }
    param_fetcher_listener: true
#    allowed_methods_listener:  true
#    routing_loader: true
#    view:
#        view_response_listener:  true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
